server:
  port: 8080

spring:
  application:
    name: CrossingTheRubicon
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true
  datasource:
    url: jdbc:postgresql://ep-silent-scene-832464.eu-central-1.aws.neon.tech/TurnBasedBackend?user=${spring.datasource.username}&password=${spring.datasource.password}
    username: jamalakh
    password: iulJ9n4cCzfV
  data:
    mongodb:
      uri: mongodb+srv://${spring.data.mongodb.username}:${spring.data.mongodb.password}@freedb.2ex7zlv.mongodb.net/${spring.data.mongodb.database}?retryWrites=true&w=majority&appName=FreeDB
      username: evilcrewstudios
      password: o695bn7r7aPyAUvV
      database: crossing_the_rubicon


application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days